### ISSUE TITLE
Twitter Authentication Dialog Don't Open

### ISSUE THREAD

**Issue by awaisraad** [spring-guides/gs-accessing-twitter#11]
Application doesn't respond to "Connect to Twitter" action! I have followed all of the steps mentioned but still no success. Are you sure that your code works?

**Comment by dsyer** [comment]
Yes, it works for me. Did you paste in your (valid) app details (consumer key and consumer secret) into application.properties? There is a companion guide that tells you how to do that: https://spring.io/guides/gs/register-twitter-app/

**Comment by gregturn** [comment]
@dsyer do you think we need a note and a link in this guide for that?

**Comment by dsyer** [comment]
I guess I thought it was there already (didn't check). The current text in this guide definitely says what you have to put where (I had to read that but to get my app to work).

**Comment by stuartblair** [comment]
@awaisraad I had the exact same issue. If you set a break point in the connect method of the ConnectController, you can see that an Exception is being thrown but not logged below.

```Java
		try {
			return new RedirectView(connectSupport.buildOAuthUrl(connectionFactory, request, parameters));
		} catch (Exception e) {
			sessionStrategy.setAttribute(request, PROVIDER_ERROR_ATTRIBUTE, e);
			return connectionStatusRedirect(providerId, request);
		}
```

Twitter is sending back an error message explaining that "I/O error on POST request for "https://api.twitter.com/oauth/request_token": cannot retry due to server authentication, in streaming mode".

Adding a callback url to the twitter app registration page fixed the problem for me. Give it a try.

I wonder if we can use something more specific than Exception? Also, I'm not clear on what setting the PROVIDER_ERROR_ATTRIBUTE has done in this case, since I didn't see any output in the browser or in the logs to suggest there was an error. It's only when you fire up the debugger you can see what's happening. Any pointers? I feel like I'm missing something.

**Comment by Fr3man** [comment]
@stuartblair Thanks for hint. It works:)

**Comment by jarvis0809** [comment]
I am trying to run the application but no success. The URL gets refreshed with "jsessionid=XYZ" appended and page remains the same. It doesn't go to twitter login page. Anyone can help?

**Comment by AshishRoy159** [comment]
Nothing is working. Tried adding the Callback URL too. Doesn't work for me.
Anyways, Twitter has 'Consumer Key' and 'Consumer Secret' but in application.properties it's 'appId' and 'appSecret'. Confusing.

**Comment by klofrau** [comment]
@AshishRoy159 appId is the Consumer Key, appSecret is the Consumer Secret. Be sure to write it like this, without brackets or quotes:

spring.social.twitter.appId=xhakjhsakjdhasd
spring.social.twitter.appSecret=Kasmndlaknsldka

I made the mistake to but the Id & Secret in double quotes, didn't work.
