### ISSUE TITLE
how to add jsp page to the project

### ISSUE THREAD

**Issue by bilani** [spring-guides/gs-accessing-twitter#9]
hi,

im nooby and using a version of your code to learn about twitter log in, im trying to add a jsp page into the code, im receiving the following error:

Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Thu Sep 03 12:16:45 EEST 2015
There was an unexpected error (type=Internal Server Error, status=500).
Error resolving template "index", template might not exist or might not be accessible by any of the configured Template Resolvers

**Comment by gregturn** [comment]
I appreciate you picking up one of our guides and attempting to tailor it for your needs. I suggest posting your question on http://stackoverflow.com and tag it as spring-boot since this is a more general purpose question on using JSPs with Spring Boot than having to do with Spring Social Twitter. It will probably facilitate a faster response from the community or the team.
